# Start with CUDA Caffe dependencies
FROM kaixhin/cuda-caffe:7.5
MAINTAINER Kai Arulkumaran <design@kaixhin.com>

RUN apt-get update && apt-get install -y \
  git \
  wget \
  bc \
  cmake \
  libatlas-base-dev \
  libatlas-dev \
  libopencv-dev \
  libprotobuf-dev \
  libgoogle-glog-dev \
  libgflags-dev \
  protobuf-compiler \
  libhdf5-dev \
  libleveldb-dev \
  liblmdb-dev \
  libsnappy-dev \
  python-dev \
  python-pip \
  python-setuptools \
  python-numpy \
  python-scipy \
  python-sklearn \
  python-tables \
  python-matplotlib \
  python-opencv \
  python-numexpr \
  cython \
  python-skimage \
  python-pil \
  gfortran > /dev/null
