# Start with CUDA Caffe dependencies
FROM kaixhin/cuda-caffe:7.5
MAINTAINER dfhe2004 <skip@skip.com>

RUN apt-get update && apt-get install -y \
  python-setuptools \
  python-scipy \
  python-sklearn \
  python-tables \
  python-matplotlib \
  python-opencv \
  python-numexpr \
  cython \
  python-skimage \
  python-pil \
   > /dev/null